version: '3.3'
services:
  db:
    image: postgres:15
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    env_file:
      - ./api/.env.db.local

  redis:
    image: redis:7.0

  api: &rails
    build:
      context: api
      target: dev
    environment:
      - PORT=80
    ports:
      - 80:80
    env_file:
      - ./api/.env.db.local
      - ./api/.env.api.local
    volumes:
      - ./api/:/app
      - gems:/gems
      - /home/akinyele/.ssh/:/root/.ssh
    stdin_open: true
    tty: true

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - redis

volumes:
  gems:
