version: '3.3'
services:
  db:
    image: postgres:15
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    env_file:
      - ./api/.env.db.local

  redis:
    image: redis:7.0

  # server:
  #   build:
  #     context: server
  #     target: dev
  #   environment:
  #     - PORT=80
  #   env_file:
  #     - ./api/.env.api.local
  #   volumes:
  #     - ./server/:/app
  #     - server_gems:/gems
  #   stdin_open: true
  #   tty: true

  api: &rails
    build:
      context: api
      target: dev
    environment:
      - PORT=80
    ports:
      - 80:80
    env_file:
      - ./api/.env.db.local
      - ./api/.env.api.local
    volumes:
      - ./api/:/app
      - gems:/gems
    depends_on:
      - db
    stdin_open: true
    tty: true

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - redis
      - db

volumes:
  gems:
  server_gems:
