# frozen_string_literal: true
source 'https://rubygems.org'

ruby '3.2.2'

gem 'sinatra'
gem 'puma', '~> 5.0'
gem 'droplet_kit', '~> 3.19'
gem 'rack-cors'
gem 'active_operation', '~> 1.0'

gem 'net-ssh', '~> 7.1'
gem 'ed25519', '~> 1.3'
gem 'bcrypt_pbkdf', '~> 1.1'

group :development do
  gem 'byebug'
end